#ASMTOOL := asminst -a x86_64_gcc -ck --
CXX := ${ASMTOOL} g++
LD := ${CXX}

#ASMTOOL_EXTRAS := 
GENFLAGS := -Wall -Wextra ${ASMTOOL_EXTRAS} -fconcepts
#LIBS :=
OPTIMIZATION_FLAGS := -O0
DEBUGGING_FLAGS := -g3
CXXFLAGS := -std=c++2a ${GENFLAGS} ${OPTIMIZATION_FLAGS} ${DEBUGGING_FLAGS}
LDFLAGS := ${LIBS} ${OPTIMIZATION_FLAGS}
